### ISSUE TITLE
Track page hits

### ISSUE THREAD

**Issue by aslakhol** [aslakhol/shera#10]
I want to know how many people visit the page and each route. I think maybe vercel gives me some stuff out of the box, but I'm going to look into it.

**Comment by FluidSense** [comment]
Jeg har brukt [Splitbee](https://splitbee.io/) med god suksess tidligere, veldig lettvint

**Comment by aslakhol** [comment]
That sounds promising, I'll check it out ^^

**Comment by aslakhol** [comment]
Implementet splitbee, it looks dope so far.
