### ISSUE TITLE
Support for ISO 8601 style week dates in date input

### ISSUE THREAD

**Issue by petterhol** [aslakhol/shera#25]
The discriminatory way the date input field is implemented only accomidates people who use "day" and "month". My suggestion is to include support for week numbers and week day numbering as explained in the ISO 8601 standard. Another explanation is available over at [pdog.no/ukekalender-om](pdog.no/ukekalender-om).

**Comment by aslakhol** [comment]
We use the browser implemented date pickers, for input on how those work please contact your browser provider, i.e. https://www.mozilla.org/en-US/contact/
