### ISSUE TITLE
Not possible to scroll/zoom on "going"-page

### ISSUE THREAD

**Issue by leifaha** [aslakhol/shera#70]
When clicking the "going" button on an event to see who is invited and who is going, it doesn't seem to be possible to scroll up/down, or to zoom in/out. Assumed to first be a problem when you exceed ~20 people.

The page also doesnt start focused on the top line. This makes it pretty hard to see who is going and who is invited (unless you do "mark all", and copy+paste the text in another editor.

Tried on both iphone, android and chrome on pc.

**Comment by aslakhol** [comment]
Ah, interesting! I pushed this right before I went on vacation so it makes sense that there are some hiccups here. 

Could you post the link to an event where you see this problem?

**Comment by aslakhol** [comment]
Resolved in #8519c9adca8a1bbab591ad5b529b1a8b959442a3 

Thanks!
