### ISSUE TITLE
Hide emails from attendees?

### ISSUE THREAD

**Issue by leifaha** [aslakhol/shera#71]
Currently, all users will get all emails. I assume the main function of the "going" pane is that people want to know who else is invited and going. Many times, emails aren't specific enough for people to read the full name. Also, not everybody might appreciate that their email is visible to all other people invited to an event they are going to.

Maybe there could be an option when adding people by email to add their name/alias, and to show this instead to any attendees?

**Comment by aslakhol** [comment]
The attendee panel shows the email as the fallback if the invited person does not have a user (or the user does not have a name set). 

However I agree that it would be nice to be able to set this name right away when inviting by email. It would also help new users fill in a name, it seems a lot of people don't notice that they can add one and I've been thinking about solutions to solve this. 

Thanks for the suggestion! I'll have a think about how I could solve this while keeping the UI simple.

**Comment by aslakhol** [comment]
Closed in favour of #88
