### ISSUE TITLE
There are currently two "new event"-buttons on the same page

### ISSUE THREAD

**Issue by mariebmo** [aslakhol/shera#94]
![image](https://github.com/user-attachments/assets/9ef786c7-c8e6-461d-8936-1ecc0960142d)

There is currently two buttons to create new events on the same page - it can be a bit confusing when there are few events, and the user might think that the "+" is supposed to do something else than "new event"

**Comment by aslakhol** [comment]
I think this one is fine for now. It looks better when people have more events and the worst case is that people click the plus and sees that it makes a new event. I'll keep the info for future redesign
