### ISSUE TITLE
[Suggestion][Feature] : Add header-image/thumbnail options for events

### ISSUE THREAD

**Issue by mariebmo** [aslakhol/shera#97]
headers/thumbnails can make it easier to differentate between events - and makes it more fun to create invites 🥳

**Comment by aslakhol** [comment]
Yes! I have a vague plan for a big "customize your event look" coming up. This kind of visual creative work is not my strongest suit so I keep pushing it in front of me, but I should get on it soon. Would love more input in general on how people should be able to change the look and feel of their events.

**Comment by aslakhol** [comment]
Closing in favour of #105. I would love input on that issue!
